name: Deploy CI/CD By Example

on:
  push:
    branches:
      - main
      - master

env:
  # Docker 账户
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_REGISTRY_URL: "registry.cn-hangzhou.aliyuncs.com" # 示例：阿里云私有镜像仓库
  # Docker 镜像地址
  DOCKER_IMAGE: "registry.cn-hangzhou.aliyuncs.com/example_namespace/example_image"
  # Docker 容器启动配置
  CONTAINER_NAME: "example_container"
  DOCKER_RUN_PARAMS: "-p 91:80 -e APP_ENV=example"
  # 服务器
  SERVER_HOST: ${{ secrets.SERVER_HOST }}
  SERVER_USER: ${{ secrets.SERVER_USER }}
  SERVER_SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}

jobs:
  CI-Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run PHP syntax check
        run: find . -type f -name "*.php" -exec php -l {} \; | tee php-syntax-check.log

      - name: Build Docker image
        run: |
          docker build -t ${{ env.DOCKER_IMAGE }} .

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}
          registry: ${{ env.DOCKER_REGISTRY_URL }} # 私有镜像仓库，需要配置此地址

      - name: Push Docker image
        run: |
          docker tag ${{ env.DOCKER_IMAGE }} ${{ env.DOCKER_IMAGE }}:latest
          docker push ${{ env.DOCKER_IMAGE }}:latest


  CD-Deploy:
    needs: CI-Build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to server
        run: |
          curl -o deploy.sh https://raw.githubusercontent.com/jefferyjob/deployments/refs/heads/main/scripts/deploy.docker.sh
          chmod +x deploy.sh
          ./deploy.sh key deploy

