name: Shell Syntax

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main

env:
  DOCKER_USERNAME: "example_docker_username"
  DOCKER_PASSWORD: "example_docker_password"
  DOCKER_REGISTRY_URL: ""
  DOCKER_IMAGE: "example_namespace/image"
  DOCKER_IMAGE_TAG: ""
  CONTAINER_NAME: "example_container"
  DOCKER_RUN_PARAMS: "-e KEY1=VAL1 -e KEY2=VAL2"
  SERVER_HOST: "example_host"
  SERVER_USER: "example_server_user"
  SERVER_PASSWORD: "example_pwd"
  SERVER_SSH_PRIVATE_KEY: "example_ssh_private_key"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up ShellCheck
        run: sudo apt-get install -y shellcheck

      - name: Find and check shell scripts
        run: |
          # Find all shell scripts and check them with shellcheck
          shellcheck -e SC2046 -e SC2317 scripts/*.sh